### ISSUE TITLE
sqlalchemy.exc.IntegrityError upon duplicate entry of username/email in database

### ISSUE THREAD

**Issue by jiekelove7** [lfelstead/CITS3403_Project#13]
Upon registering with a pre-existing username/email raises this exception:

> sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email
> [SQL: INSERT INTO user (username, email, password, about_me, last_seen) VALUES (?, ?, ?, ?, ?)]
> (Background on this error at: http://sqlalche.me/e/14/gkpj)

To replicate:
- Register with a duplicate username or email e.g test@test.com (Already comitted to origin)
100% replication rate

Traceback:
![Traceback](https://i.imgur.com/TAO4qzl.png)

**Comment by lfelstead** [comment]
Fixed now. I had changed a part in forms.py when adding flash messages earlier today which caused this error to appear.
