### ISSUE TITLE
FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS

### ISSUE THREAD

**Issue by jiekelove7** [lfelstead/CITS3403_Project#3]
Upon launch of the application via run.py the following warning is printed to shell:
"FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.                                                                                                                                                       warnings.warn(FSADeprecationWarning( "

Unknown if this is a problem or not but here's a related thread that may be of use:
https://stackoverflow.com/questions/33738467/how-do-i-know-if-i-can-disable-sqlalchemy-track-modifications

**Comment by lfelstead** [comment]
Added a line to init file to disable SQLALCHEMY_TRACK_MODIFICATIONS so the warning no longer appears.
